import { z } from 'zod';

/**
 * Marketing tag configuration: typed, format-validated provider IDs.
 *
 * There is deliberately **no free-form script field** anywhere in this feature.
 * A "paste your snippet here" box in an e-commerce admin is a card-skimming
 * vector: any staff account — or one stolen session — could inject a script that
 * reads the checkout form and posts card details elsewhere, and the site would
 * keep working normally so nobody would notice. Every script on the page is
 * generated by our own code from an ID that matched a strict pattern.
 *
 * The patterns below are therefore a security control, not a convenience: they
 * are what stops `"><script>` from ever reaching the page. Anything exotic a
 * client needs goes inside GTM, which is what GTM is for.
 *
 * This module is import-safe from client components: it holds no secrets and
 * touches no database.
 */

// ─── Field patterns ──────────────────────────────────────────────────────────

/**
 * One row per provider. `pattern` is enforced server-side and shown to the
 * operator as a hint, so the format they see is the format that is checked.
 */
export const TAG_FIELDS = {
  gtmId: {
    label: 'Google Tag Manager ID',
    pattern: /^GTM-[A-Z0-9]{6,9}$/,
    hint: 'GTM-XXXXXXX',
    help: 'Google Tag Manager → Workspace → container ID, top right.',
    helpUrl: 'https://tagmanager.google.com/',
  },
  ga4MeasurementId: {
    label: 'GA4 Measurement ID',
    pattern: /^G-[A-Z0-9]{8,12}$/,
    hint: 'G-XXXXXXXXXX',
    help: 'Google Analytics → Admin → Data streams → your web stream.',
    helpUrl: 'https://analytics.google.com/',
  },
  googleAdsId: {
    label: 'Google Ads conversion ID',
    pattern: /^AW-\d{9,12}$/,
    hint: 'AW-XXXXXXXXX',
    help: 'Google Ads → Goals → Conversions → your action → tag setup.',
    helpUrl: 'https://ads.google.com/',
  },
  googleAdsLabel: {
    label: 'Google Ads conversion label',
    pattern: /^[A-Za-z0-9_-]{5,40}$/,
    hint: 'AbC-D_efG12hIjKlM',
    help: 'Shown next to the conversion ID in the same tag setup screen.',
    helpUrl: 'https://ads.google.com/',
  },
  googleSiteVerification: {
    label: 'Google site verification',
    pattern: /^[A-Za-z0-9_-]{20,60}$/,
    hint: 'The content value only, not the whole meta tag',
    help: 'Search Console → Settings → Ownership verification → HTML tag.',
    helpUrl: 'https://search.google.com/search-console',
  },
  metaPixelId: {
    label: 'Meta Pixel ID',
    pattern: /^\d{15,16}$/,
    hint: '15–16 digits',
    help: 'Meta Events Manager → Data sources → your pixel.',
    helpUrl: 'https://business.facebook.com/events_manager2/',
  },
  clarityProjectId: {
    label: 'Microsoft Clarity project ID',
    pattern: /^[a-z0-9]{8,12}$/,
    hint: 'Lowercase letters and digits',
    help: 'Clarity → Settings → Overview → project ID.',
    helpUrl: 'https://clarity.microsoft.com/',
  },
  hotjarSiteId: {
    label: 'Hotjar Site ID',
    pattern: /^\d{6,9}$/,
    hint: '6–9 digits',
    help: 'Hotjar → Settings → Sites & organisations.',
    helpUrl: 'https://insights.hotjar.com/',
  },
  pinterestTagId: {
    label: 'Pinterest Tag ID',
    pattern: /^\d{13}$/,
    hint: '13 digits',
    help: 'Pinterest Ads → Conversions → Tag manager.',
    helpUrl: 'https://ads.pinterest.com/',
  },
  tiktokPixelId: {
    label: 'TikTok Pixel ID',
    pattern: /^[A-Z0-9]{20}$/,
    hint: '20 uppercase letters and digits',
    help: 'TikTok Ads Manager → Assets → Events → Web events.',
    helpUrl: 'https://ads.tiktok.com/',
  },
  snapPixelId: {
    label: 'Snap Pixel ID',
    pattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
    hint: 'UUID, e.g. 0f1e2d3c-4b5a-6978-8796-a5b4c3d2e1f0',
    help: 'Snapchat Ads → Events Manager → your pixel.',
    helpUrl: 'https://ads.snapchat.com/',
  },
} as const;

export type TagFieldKey = keyof typeof TAG_FIELDS;

export const TAG_FIELD_KEYS = Object.keys(TAG_FIELDS) as TagFieldKey[];

// ─── Consent ─────────────────────────────────────────────────────────────────

export const CONSENT_MODES = ['REQUIRED', 'IMPLIED', 'OFF'] as const;
export type ConsentMode = (typeof CONSENT_MODES)[number];

export const CONSENT_MODE_LABELS: Record<ConsentMode, string> = {
  REQUIRED: 'Required — nothing loads until the visitor accepts',
  IMPLIED: 'Implied — tags load immediately, banner is informational',
  OFF: 'Off — no banner (only if consent is handled elsewhere)',
};

// ─── Validation ──────────────────────────────────────────────────────────────

/**
 * An optional ID field. An empty submission stores NULL — meaning "tag off" —
 * rather than an empty string, which would render a broken script tag.
 *
 * A value that does not match is **rejected with a message**, never silently
 * stripped: quietly removing characters would leave the operator staring at a
 * tag that looks configured and does nothing.
 */
function idField(key: TagFieldKey) {
  const { pattern, label, hint } = TAG_FIELDS[key];
  return z
    .string()
    .trim()
    .transform((v) => (v === '' ? null : v))
    .refine((v) => v === null || pattern.test(v), {
      message: `${label} must look like ${hint}`,
    });
}

/** Shape accepted from the admin form. */
export const marketingTagsSchema = z
  .object({
    gtmId: idField('gtmId'),
    ga4MeasurementId: idField('ga4MeasurementId'),
    googleAdsId: idField('googleAdsId'),
    googleAdsLabel: idField('googleAdsLabel'),
    googleSiteVerification: idField('googleSiteVerification'),
    metaPixelId: idField('metaPixelId'),
    metaCapiEnabled: z.coerce.boolean(),
    clarityProjectId: idField('clarityProjectId'),
    hotjarSiteId: idField('hotjarSiteId'),
    pinterestTagId: idField('pinterestTagId'),
    tiktokPixelId: idField('tiktokPixelId'),
    snapPixelId: idField('snapPixelId'),
    consentMode: z.enum(CONSENT_MODES),
    consentBannerText: z
      .string()
      .trim()
      .max(400)
      .transform((v) => (v === '' ? null : v)),
  })
  .refine((v) => !(v.googleAdsLabel && !v.googleAdsId), {
    message: 'A Google Ads conversion label needs a conversion ID as well',
    path: ['googleAdsLabel'],
  });

export type MarketingTagsInput = z.infer<typeof marketingTagsSchema>;

/**
 * The CAPI access token. Validated loosely on purpose — Meta does not publish a
 * stable format and rejecting a valid token would be worse than accepting an
 * invalid one, which simply fails at send time and is logged.
 */
export const capiTokenSchema = z
  .string()
  .trim()
  .min(20, 'That does not look like a CAPI access token')
  .max(512)
  .regex(/^[A-Za-z0-9_.\-|]+$/, 'That does not look like a CAPI access token');

// ─── Public (browser-safe) projection ────────────────────────────────────────

/**
 * Exactly what the browser is allowed to know.
 *
 * `metaCapiToken` is structurally absent from this type — not merely omitted at
 * one call site — so no future edit can leak it into a client payload by
 * forgetting to strip a field. The token is read only by server code that talks
 * to Meta directly.
 */
export type PublicTagConfig = {
  gtmId: string | null;
  ga4MeasurementId: string | null;
  googleAdsId: string | null;
  googleAdsLabel: string | null;
  googleSiteVerification: string | null;
  metaPixelId: string | null;
  clarityProjectId: string | null;
  hotjarSiteId: string | null;
  pinterestTagId: string | null;
  tiktokPixelId: string | null;
  snapPixelId: string | null;
  consentMode: ConsentMode;
  consentBannerText: string | null;
};

export const EMPTY_TAG_CONFIG: PublicTagConfig = {
  gtmId: null,
  ga4MeasurementId: null,
  googleAdsId: null,
  googleAdsLabel: null,
  googleSiteVerification: null,
  metaPixelId: null,
  clarityProjectId: null,
  hotjarSiteId: null,
  pinterestTagId: null,
  tiktokPixelId: null,
  snapPixelId: null,
  consentMode: 'REQUIRED',
  consentBannerText: null,
};

/**
 * Re-validate on the way out as well as on the way in.
 *
 * The database is not the trust boundary the page is: a value could have been
 * written by an older build, a manual SQL edit, or a restored backup. Anything
 * that does not match its pattern is dropped rather than rendered, so a
 * malformed value can never reach a script tag even if it reached the table.
 */
export function toPublicTagConfig(row: Record<string, unknown> | null): PublicTagConfig {
  if (!row) return EMPTY_TAG_CONFIG;

  const clean = (key: TagFieldKey): string | null => {
    const value = row[key];
    if (typeof value !== 'string') return null;
    const trimmed = value.trim();
    if (trimmed === '') return null;
    return TAG_FIELDS[key].pattern.test(trimmed) ? trimmed : null;
  };

  const mode = row.consentMode;
  const consentMode: ConsentMode =
    typeof mode === 'string' && (CONSENT_MODES as readonly string[]).includes(mode)
      ? (mode as ConsentMode)
      : 'REQUIRED';

  const bannerText = typeof row.consentBannerText === 'string' ? row.consentBannerText.trim() : '';

  return {
    gtmId: clean('gtmId'),
    ga4MeasurementId: clean('ga4MeasurementId'),
    googleAdsId: clean('googleAdsId'),
    googleAdsLabel: clean('googleAdsLabel'),
    googleSiteVerification: clean('googleSiteVerification'),
    metaPixelId: clean('metaPixelId'),
    clarityProjectId: clean('clarityProjectId'),
    hotjarSiteId: clean('hotjarSiteId'),
    pinterestTagId: clean('pinterestTagId'),
    tiktokPixelId: clean('tiktokPixelId'),
    snapPixelId: clean('snapPixelId'),
    consentMode,
    consentBannerText: bannerText === '' ? null : bannerText.slice(0, 400),
  };
}

// ─── Derived state ───────────────────────────────────────────────────────────

/**
 * GTM supersedes the direct tags.
 *
 * Firing the same purchase from GTM *and* a directly-installed tag is the most
 * common tracking mistake there is, and it silently doubles every conversion —
 * which corrupts the ROAS numbers the client uses to decide ad spend. When a GTM
 * container is present we load only GTM and configure the rest inside it.
 */
export function gtmSupersedes(config: PublicTagConfig): TagFieldKey[] {
  if (!config.gtmId) return [];
  return (['ga4MeasurementId', 'googleAdsId', 'metaPixelId'] as const).filter((k) => config[k] !== null);
}

/** Tags that will actually load, for the admin's "what's live" summary. */
export function activeTags(config: PublicTagConfig): { key: TagFieldKey; label: string; value: string }[] {
  const superseded = new Set<TagFieldKey>(gtmSupersedes(config));
  return TAG_FIELD_KEYS.filter((key) => config[key] !== null && !superseded.has(key)).map((key) => ({
    key,
    label: TAG_FIELDS[key].label,
    value: String(config[key]),
  }));
}

/** True when nothing at all is configured — used to keep the CSP untouched. */
export function hasAnyTag(config: PublicTagConfig): boolean {
  return TAG_FIELD_KEYS.some((key) => config[key] !== null);
}

/** Mask a stored secret for display: never send the real value to the browser. */
export function maskSecret(value: string | null | undefined): string | null {
  if (!value) return null;
  return `••••${value.slice(-4)}`;
}
